name: drug_discovery
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - babel=2.17.0
  - biopython=1.85
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.14
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mdtraj==1.10.3
  - meeko=0.7.1
  - nglview=3.1.4
  - notebook=7.4.1
  - numpy=1.26.4
  - openbabel=3.1.1
  - openmm=8.2.0
  - pandas=2.2.3
  - python=3.9.21
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - pip:
      - rdkit==2024.9.6
      - vina==1.2.7
prefix: /opt/anaconda3/envs/drug_discovery
