name: drug_discovery
channels:
  - bioconda
  - conda-forge
  - omnia
  - defaults
dependencies:
  - alabaster=0.7.16
  - anyio=4.9.0
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - autodock-vina=1.1.2
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - biopython=1.85
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - boost-cpp=1.82.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - docutils=0.21.2
  - exceptiongroup=1.2.2
  - executing=2.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.94
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.57.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - freetype-py=2.3.0
  - fribidi=1.0.16
  - gemmi=0.7.3
  - gettext=0.21.0
  - glib=2.84.2
  - glib-tools=2.84.2
  - graphite2=1.3.14
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.6.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.18.1
  - ipywidgets=8.1.6
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.14
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.3.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-python=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.3
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.84.2
  - libiconv=1.18
  - libintl=0.23.1
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libntlm=1.8
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libsodium=1.0.20
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - llvm-openmp=20.1.3
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - meeko=0.7.1
  - micromamba=2.4.0
  - mistune=3.1.3
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nglview=3.1.4
  - notebook=7.4.1
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - ocl_icd_wrapper_apple=1.0.0
  - openbabel=3.1.1
  - opencl-headers=2024.10.24
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openmm=8.2.0
  - openssl=3.6.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre=8.45
  - pcre2=10.42
  - pdbfixer=1.11
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.0.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - prody=2.4.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycairo=1.23.0
  - pycparser=2.22
  - pygments=2.19.1
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - rav1e=0.7.1
  - readline=8.2
  - referencing=0.36.2
  - reportlab=4.4.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rlpycairo=0.2.0
  - rpds-py=0.24.0
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - send2trash=1.8.3
  - setuptools=79.0.1
  - six=1.17.0
  - sniffio=1.3.1
  - snowballstemmer=3.0.1
  - soupsieve=2.5
  - sphinx=7.4.7
  - sphinx_rtd_theme=3.0.2
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.50.2
  - stack_data=0.6.3
  - svt-av1=3.1.2
  - swig=3.0.8
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zlib-ng=2.2.5
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - bel-resources==0.0.3
      - bioregistry==0.12.11
      - cftime==1.6.4.post1
      - click==8.1.8
      - click-plugins==1.1.1
      - curies==0.10.13
      - dnspython==2.7.0
      - email-validator==2.2.0
      - eval-type-backport==0.2.2
      - greenlet==3.2.1
      - humanize==4.12.2
      - mdtraj==1.10.3
      - more-click==0.1.2
      - more-itertools==10.7.0
      - multisplitby==0.0.1
      - netcdf4==1.7.2
      - networkx==3.2.1
      - psycopg2-binary==2.9.10
      - pybel==0.15.5
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pystow==0.7.0
      - pytrie==0.4.0
      - ratelimit==2.2.1
      - rdkit==2024.9.6
      - requests-file==2.1.0
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.40
      - tabulate==0.9.0
      - tqdm==4.67.1
      - typing-inspection==0.4.0
      - vina==1.2.7
prefix: /opt/anaconda3/envs/drug_discovery
